[package]
name = "image_to_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
gltf = "1.0.0"
gltf-json = "1.0.0"
image = "0.24.3"
