[package]
name = "fmc_protocol_derive"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/formulaicgame/fmc_protocol"
description = "Derive macros for fmc_protocol"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
