name: release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: fmc-linux
            # TODO: When this is run on macos-latest it says the toolchain is missing. It has worked before I think. 
            # macos-latest has m1 cpus but I think they should be able to do it.
          - target: x86_64-apple-darwin
            os: macos-13
            name: fmc-macos-intel
          - target: aarch64-apple-darwin
            os: macos-latest
            name: fmc-macos-arm
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: fmc-windows
            file_extension: .exe
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: ${{ matrix.target }}

      - name: Install dependencies
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu'}}
        run: sudo apt-get update && sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Build
        run: cd client && cargo build --release --target ${{ matrix.target }}

      - name: Rename Artifact
        run: cp ./client/target/${{ matrix.target }}/release/client${{ matrix.file_extension }} ${{ matrix.name }}${{ matrix.file_extension }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}${{ matrix.file_extension }}
          retention-days: 1

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    name: Create Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: mkdir artifacts

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*/*"
          allowUpdates: true
          removeArtifacts: true
          tag: ${{ github.event.inputs.tag_name }}
